let express = require('express')
let router = express.Router()
let user= require('./API/user')
let new_sample = require('./API/list')
let tagged_sample = require('./API/tagged_list')
let ballot = require('./API/ballot')

router.get('/user', user.get)
router.get('/list/all', new_sample.all)
router.get('/list/get', new_sample.get)
router.get('/list/add', new_sample.add)
router.get('/list/update', new_sample.update)
router.get('/list/del', new_sample.del)
router.get('/list/show', new_sample.show)
router.get('/list/joinpair', new_sample.joinpair)
router.get('/list/previous', new_sample.previous)
router.get('/list/next', new_sample.next)
router.get('/list/tmp', new_sample.tmp)
router.get('/list/updaterank', new_sample.updaterank)
router.get('/list/getsamplecnt', new_sample.getsamplecnt)
router.get('/list/getcorrectcnt', new_sample.getcorrectcnt)
router.get('/list/gettreecnt', new_sample.gettreecnt)
router.get('/list/getMaxTreeDepth', new_sample.getMaxTreeDepth)
router.get('/list/getMaxChildrenNum', new_sample.getMaxChildrenNum)
router.get('/list/maxid', new_sample.maxid)
router.get('/list/download', new_sample.download)
router.get('/list/tree', new_sample.tree)

router.get('/tagged_list/all', tagged_sample.all)
router.get('/tagged_list/get', tagged_sample.get)
router.get('/tagged_list/add', tagged_sample.add)
router.get('/tagged_list/update', tagged_sample.update)
router.get('/tagged_list/del', tagged_sample.del)
router.get('/tagged_list/download', tagged_sample.download)
router.get('/tagged_list/min', tagged_sample.min)

router.get('/ballot/addballot', ballot.addballot)
router.get('/ballot/maxballot', ballot.maxballot)

module.exports = router
